name: Build and release

on: push

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the executable
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Package the executable
        run: npm run package

      - name: Release the app
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./out/make/*